services:
  - type: web
    name: eng-hub-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: SESSION_SECRET
        value: "your-secret-here"
      - key: NODE_ENV
        value: "production"
  - type: static_site
    name: eng-hub-frontend
    staticPublishPath: frontend/public
    buildCommand: npm install
    env: static
    plan: free
